### ISSUE TITLE
Schema format for user.status

### ISSUE THREAD

**Issue by chongwang87** [Meteor-Community-Packages/meteor-user-status#60]
Please provide doc for collection Schema for user.status

**Comment by praneybehl** [comment]
I am trying to figure that too...  Since I am using Collection2, installing this package gives errors straight away:


W20150618-12:42:45.768(10)? (STDERR) Error: status.idle is not allowed by the schema

W20150618-12:42:45.768(10)? (STDERR)     at getErrorObject (packages/aldeed:collection2/collection2.js:369:1)
W20150618-12:42:45.768(10)? (STDERR)     at [object Object].doValidate (packages/aldeed:collection2/collection2.js:352:1)

W20150618-12:42:45.768(10)? (STDERR)     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2/collection2.js:154:1)

W20150618-12:42:45.768(10)? (STDERR)     at onStartup (packages/mizzao:user-status/status.coffee:102:16)


Some help shall be highly appreciated.

**Comment by praneybehl** [comment]
Alright using : 
          status: {
              type: Object,
              optional: true,
              blackbox: true
          }
fixed the errors, Will report any other issues as they occur, thanks.

**Comment by lpatmo** [comment]
I just got this error too. @praneybehl How did you fix it?

```Error: status.idle is not allowed by the schema
    at getErrorObject (packages/aldeed_collection2/packages/aldeed_collection2.js:425:1)
    at [object Object].doValidate (packages/aldeed_collection2/packages/aldeed_collection2.js:408:1)
    at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2/packages/aldeed_collection2.js:177:1)
    at onStartup (packages/mizzao_user-status/status.coffee:102:16)
    at /Users/lindapeng/Desktop/lindaprojects/meteor/cb-v2/.meteor/local/build/programs/server/boot.js:249:5
Exited with code: 8
Your application is crashing. Waiting for file change.
Unexpected mongo exit code 0. Restarting.```

**Comment by mizzao** [comment]
See also #67.

**Comment by MichaelJCole** [comment]
I've been using this:

```
// Status module information  https://github.com/mizzao/meteor-user-status#basic-usage---online-state
  // Public and sent to any client

  'status':                  { type: Object, optional: true },
  'status.lastLogin.date':   { type: Date, optional: true },
  'status.lastLogin.ipAddr': { type: String, optional: true },
  'status.userAgent':        { type: String, optional: true },
  'status.idle':             { type: Boolean, optional: true },
  'status.lastActivity':     { type: Date, optional: true },
  'status.online': {
    type: Boolean,
    index: true,
    optional: true,
  },
```

**Comment by StorytellerCZ** [comment]
Anyone interested in adding the schema to the docs?
